### ISSUE TITLE
URL failed 

### ISSUE THREAD

**Issue by Sicheng2000** [Sicheng2000/project#1]
Professor Francom, another problem just arose, now my URL link cannot link to my output. @francojc
<img width="547" alt="404" src="https://github.com/Sicheng2000/project/assets/157050571/bd8a0b78-0449-4d52-943b-be6fd64a3716">

**Comment by francojc** [comment]
@Sicheng2000 It looks like that in your `_quarto.yml` document you have this code: https://github.com/Sicheng2000/project/blob/e83210c0336b69a2190e0db0b404fe92938a8f07/_quarto.yml#L9-L10

However, these addresses should be switched. 

```yaml
 site-url: "https://sicheng2000.github.io/project/" # Website URL 
 repo-url: https://github.com/Sicheng2000/project # Repository URL 
 ```
This should fix the issue.

**Comment by Sicheng2000** [comment]
@francojc, Professor Fancom, I have switched it. But it did not look like it worked.
<img width="348" alt="image" src="https://github.com/Sicheng2000/project/assets/157050571/b62922ae-1539-4153-81ea-a9691636cb34">
<img width="652" alt="image" src="https://github.com/Sicheng2000/project/assets/157050571/60dc1537-7664-4257-83c3-f58fe4df38f4">

**Comment by francojc** [comment]
This may be related to you running the `./set-publish-gh-pages` the second time. If you have a chance, this might be something that we can work out quicker face-to-face or on Zoom synchronously. If you can [set up a time with me on my appointment calendar](https://cal.com/francojc/meeting?date=2024-02-23&month=2024-02), that would be great.

**Comment by Sicheng2000** [comment]
Sure! Thanks, Professor Francom. So could I just submit my "error" URL first, and resubmit later until we figure it out?@fancojc

**Comment by francojc** [comment]
Yes, even though the webpage is not showing, I can access your files and render the website on my local machine and give you feedback. 

My hunch is running the script the second time has confused GitHub in terms of how to display your actual web address --not something that you can fix without some guidance.

So, feel free to submit your repo address in Canvas to let me know you are ready for my review and feedback. ✅

**Comment by Sicheng2000** [comment]
Thank you so much, Professor Francom! It's like if I make one step wrong, I just cannot revert to the original path.😂 @francojc
